test7

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -99,3 +99,43 @@ jobs:
           curl -s -X POST http://localhost:8081/shorten \
           -H "Content-Type: application/json" \
           -d '{"long_url":"https://smashkarts.io"}'
+
+  test:
+    needs: deploy
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Test deployed app (send 100 POST requests)
+        run: |
+          # Start a background process to send requests
+          for i in {1..100}; do
+            curl -s -X POST http://localhost:8081/shorten \
+            -H "Content-Type: application/json" \
+            -d '{"long_url":"https://www.amazon.in/Daikin-Inverter-Display-Technology-MTKL50U/dp/B0BK1KS6ZD/?_encoding=UTF8&ref_=pd_hp_d_btf_ci_mcx_mr_ca_id_hp_d"}' &
+            sleep 0.01
+          done
+          # Wait for all background jobs to finish
+          wait
+
+      - name: Check if all requests returned status 200
+        run: |
+          SUCCESS=true
+          for i in {1..100}; do
+            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8081/shorten \
+            -H "Content-Type: application/json" \
+            -d '{"long_url":"https://www.amazon.in/Daikin-Inverter-Display-Technology-MTKL50U/dp/B0BK1KS6ZD/?_encoding=UTF8&ref_=pd_hp_d_btf_ci_mcx_mr_ca_id_hp_d"}')
+            
+            if [[ "$HTTP_STATUS" != "200" ]]; then
+              echo "Test failed for request $i: HTTP status is $HTTP_STATUS"
+              SUCCESS=false
+            fi
+          done
+
+          if [ "$SUCCESS" = false ]; then
+            exit 1
+          else
+            echo "All tests passed: HTTP status 200 for all requests"
+          fi
